/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import rojeru_san.efectos.ValoresEnum;

/**
 *
 * @author chave
 */
public class CrearCuenta extends javax.swing.JFrame {
    
    /**
     * Creates new form CrearCuenta
     */
    boolean correoValidado;
    boolean usuarioValidado;
     String codigo ;
     IniciarSesion padre;
    public CrearCuenta(IniciarSesion padre) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.padre= padre;
        correoValidado = false;
        usuarioValidado = false;
        lblverificarCodigo.setVisible(false);
        lblverificarUsername.setVisible(false);
        lblErrorUser.setVisible(false);
        lblErrorCodigo.setVisible(false);
        btnOcultar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcrearCuenta = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lbldni = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblcontraseña = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtCodigo = new javax.swing.JTextField();
        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JLabel();
        btnBuscarDni = new javax.swing.JLabel();
        btbEnviarCodigo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        lblcontraseña1 = new javax.swing.JLabel();
        lblverificarCodigo = new necesario.LabelIcon();
        lblverificarUsername = new necesario.LabelIcon();
        txtCargo = new javax.swing.JTextField();
        btnOcultar = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        txtTelefono = new necesario.TextField();
        lblErrorUser = new javax.swing.JLabel();
        lblErrorCodigo = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        rSButtonShape7 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape16 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape17 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape18 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape19 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape20 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape21 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape22 = new RSMaterialComponent.RSButtonShape();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(41, 41, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcrearCuenta.setBackground(new java.awt.Color(41, 41, 51));
        lblcrearCuenta.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblcrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblcrearCuenta.setText("Crear Cuenta");
        lblcrearCuenta.setOpaque(true);
        jPanel1.add(lblcrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 24, -1, -1));

        lblcorreo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblcorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblcorreo.setText("Correo");
        jPanel1.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.setSelectionColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 260, 32));

        lbldni.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbldni.setForeground(new java.awt.Color(255, 255, 255));
        lbldni.setText("Ingrese Dni:");
        jPanel1.add(lbldni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos");
        jPanel1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setEnabled(false);
        txtApellidos.setSelectionColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 280, 32));

        lblDireccion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Cargo");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 302, -1, -1));

        lblnombres.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblnombres.setForeground(new java.awt.Color(255, 255, 255));
        lblnombres.setText("Nombres ");
        jPanel1.add(lblnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtNombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setEnabled(false);
        txtNombres.setSelectionColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 280, 32));

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Ingrese Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, 20));

        txtDni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtDni.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDni.setSelectionColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 102, 190, 32));

        lblcontraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblcontraseña.setText("Contraseña");
        jPanel1.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        lblCelular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("Celular");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 20));

        txtContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtContraseña.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtContraseña.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtContraseña.setEchoChar('●');
        txtContraseña.setSelectionColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 260, 30));

        txtCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 260, 32));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32wtminimize-sign.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32wtclose.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(0, 153, 0));
        btnAceptar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("Aceptar");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setOpaque(true);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 250, 40));

        btnBuscarDni.setBackground(new java.awt.Color(41, 41, 51));
        btnBuscarDni.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnBuscarDni.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarDni.setText("Buscar");
        btnBuscarDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnBuscarDni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarDni.setOpaque(true);
        btnBuscarDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarDniMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, 40));

        btbEnviarCodigo.setBackground(new java.awt.Color(47, 47, 213));
        btbEnviarCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btbEnviarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btbEnviarCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btbEnviarCodigo.setText("Enviar Código");
        btbEnviarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btbEnviarCodigo.setOpaque(true);
        btbEnviarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbEnviarCodigoMouseClicked(evt);
            }
        });
        jPanel1.add(btbEnviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 230, 40));

        btnCancelar.setBackground(new java.awt.Color(227, 17, 59));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setOpaque(true);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 501, 250, 40));

        lblcontraseña1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblcontraseña1.setForeground(new java.awt.Color(255, 255, 255));
        lblcontraseña1.setText("Nombre de Usuario");
        jPanel1.add(lblcontraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        lblverificarCodigo.setForeground(new java.awt.Color(204, 0, 0));
        lblverificarCodigo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ERROR);
        lblverificarCodigo.setOpaque(true);
        lblverificarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblverificarCodigoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblverificarCodigoMouseExited(evt);
            }
        });
        jPanel1.add(lblverificarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 32, 32));

        lblverificarUsername.setForeground(new java.awt.Color(204, 0, 0));
        lblverificarUsername.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ERROR);
        lblverificarUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblverificarUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblverificarUsernameMouseExited(evt);
            }
        });
        jPanel1.add(lblverificarUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 32, 32));

        txtCargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCargo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtCargo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCargo.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCargoKeyReleased(evt);
            }
        });
        jPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 339, 280, 32));

        btnOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32wthide.png"))); // NOI18N
        btnOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOcultarMouseClicked(evt);
            }
        });
        jPanel1.add(btnOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32wtshow.png"))); // NOI18N
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        jPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        txtTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTelefono.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.setPlaceholder("");
        txtTelefono.setSoloNumeros(true);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 280, 30));

        lblErrorUser.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrorUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorUser.setText("Este nombre ya esta en uso");
        lblErrorUser.setOpaque(true);
        jPanel1.add(lblErrorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 190, -1));

        lblErrorCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrorCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorCodigo.setText("El codigo es incorrecto");
        lblErrorCodigo.setOpaque(true);
        jPanel1.add(lblErrorCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 160, -1));

        txtUsername1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUsername1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtUsername1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsername1.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtUsername1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsername1KeyReleased(evt);
            }
        });
        jPanel1.add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 260, 32));

        rSButtonShape7.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape7.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape7.setBorderPainted(false);
        rSButtonShape7.setDefaultCapable(false);
        rSButtonShape7.setFocusPainted(false);
        rSButtonShape7.setFocusable(false);
        jPanel1.add(rSButtonShape7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 50, 30));

        rSButtonShape16.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape16.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape16.setBorderPainted(false);
        rSButtonShape16.setDefaultCapable(false);
        rSButtonShape16.setFocusPainted(false);
        rSButtonShape16.setFocusable(false);
        jPanel1.add(rSButtonShape16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 20, 30));

        rSButtonShape17.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape17.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape17.setBorderPainted(false);
        rSButtonShape17.setDefaultCapable(false);
        rSButtonShape17.setFocusPainted(false);
        rSButtonShape17.setFocusable(false);
        jPanel1.add(rSButtonShape17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 20, 30));

        rSButtonShape18.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape18.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape18.setBorderPainted(false);
        rSButtonShape18.setDefaultCapable(false);
        rSButtonShape18.setFocusPainted(false);
        rSButtonShape18.setFocusable(false);
        jPanel1.add(rSButtonShape18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 20, 30));

        rSButtonShape19.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape19.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape19.setBorderPainted(false);
        rSButtonShape19.setDefaultCapable(false);
        rSButtonShape19.setFocusPainted(false);
        rSButtonShape19.setFocusable(false);
        jPanel1.add(rSButtonShape19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 20, 30));

        rSButtonShape20.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape20.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape20.setBorderPainted(false);
        rSButtonShape20.setDefaultCapable(false);
        rSButtonShape20.setFocusPainted(false);
        rSButtonShape20.setFocusable(false);
        jPanel1.add(rSButtonShape20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 50, 30));

        rSButtonShape21.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape21.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape21.setBorderPainted(false);
        rSButtonShape21.setDefaultCapable(false);
        rSButtonShape21.setFocusPainted(false);
        rSButtonShape21.setFocusable(false);
        jPanel1.add(rSButtonShape21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 50, 30));

        rSButtonShape22.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape22.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape22.setBorderPainted(false);
        rSButtonShape22.setDefaultCapable(false);
        rSButtonShape22.setFocusPainted(false);
        rSButtonShape22.setFocusable(false);
        jPanel1.add(rSButtonShape22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        lblverificarCodigo.setVisible(true);
        if(txtCodigo.getText().equals(codigo)){
            correoValidado = true;
            lblverificarCodigo.setForeground(Color.green);
            lblverificarCodigo.setIcons(ValoresEnum.ICONS.VERIFIED_USER);
        }else{
            correoValidado = false;
            lblverificarCodigo.setForeground(Color.red);
            lblverificarCodigo.setIcons(ValoresEnum.ICONS.ERROR);
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        padre.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        /*if(validarCampos()){
            try {
                cargarDatos();
                servicio.insertarCuenta(user);
                login.setVisible(true);
                mensaje.cargarDatos("Crear Cuenta","La cuenta se creo "
                    + "correctamente", 1);
                this.dispose();
            } catch (SQLException ex) {
                mensaje.cargarDatos("Crear Cuenta", "No se pudo crear la cuenta."
                    , 1);
            }
        }else{
            mensaje.cargarDatos("Crear Cuenta"
                ,"Completa todos los campos.",1);
        }*/
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnBuscarDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDniMouseClicked
       /* user= new Usuario();
        String dni = txtDni.getText().trim();
        if(dni.length()==8){
            if(servicio.verificarCampo("idUsuario",dni)){
                mensaje.cargarDatos("Verificar Dni"
                    ,"Ya existe una cuenta con el dni ingresado.",1);
            }else {
                user = Dni.getDatos(dni);
                if(user!=null)
                cargarDatos(user);
            }
        }else{
            mensaje.cargarDatos("Verificar Edad"
                ,"El campo dni debe ser de longitud 8",1);
        }*/
    }//GEN-LAST:event_btnBuscarDniMouseClicked

    private void btbEnviarCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbEnviarCodigoMouseClicked
        if(!txtCorreo.getText().isEmpty())
        {
            String correo = txtCorreo.getText().trim();
            /*if(servicio.verificarCampo("correo",correo)){
                mensaje.cargarDatos("Verificar Correo"
                    ,"Ya existe una cuenta con el correo ingresado.",1);
            }
            else {

                /*try {
                    //codigo = Correo.enviarCorreoElectronico(correo);
                } catch (MessagingException ex) {
                    //mensaje.cargarDatos("Verificar Correo"
                      //  ,"No se pudo enviar el código.",1);
                }
            }*/
        }else{
           // mensaje.cargarDatos("Verificar Correo"
             //   ,"Complete el campo correo",1);
        }
    }//GEN-LAST:event_btbEnviarCodigoMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void lblverificarUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblverificarUsernameMouseEntered
        if(lblverificarUsername.getIcons().equals(ValoresEnum.ICONS.ERROR))
        lblErrorUser.setVisible(true);
    }//GEN-LAST:event_lblverificarUsernameMouseEntered

    private void lblverificarUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblverificarUsernameMouseExited
        if(lblverificarUsername.getIcons().equals(ValoresEnum.ICONS.ERROR))
        lblErrorUser.setVisible(false);
    }//GEN-LAST:event_lblverificarUsernameMouseExited

    private void lblverificarCodigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblverificarCodigoMouseEntered
        if(lblverificarCodigo.getIcons().equals(ValoresEnum.ICONS.ERROR))
        lblErrorCodigo.setVisible(true);
    }//GEN-LAST:event_lblverificarCodigoMouseEntered

    private void lblverificarCodigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblverificarCodigoMouseExited
        if(lblverificarCodigo.getIcons().equals(ValoresEnum.ICONS.ERROR))
        lblErrorCodigo.setVisible(false);
    }//GEN-LAST:event_lblverificarCodigoMouseExited

    private void txtCargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyReleased

        lblverificarUsername.setVisible(true);
        /*if(!servicio.verificarCampo("username", txtCargo.getText())){
            usuarioValidado = true;
            lblverificarUsername.setForeground(Color.green);
            lblverificarUsername.setIcons(ValoresEnum.ICONS.VERIFIED_USER);
        }else{
            usuarioValidado = false;
            lblverificarUsername.setForeground(Color.red);
            lblverificarUsername.setIcons(ValoresEnum.ICONS.ERROR);
        }*/

    }//GEN-LAST:event_txtCargoKeyReleased

    private void btnOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseClicked
        btnVer.setVisible(true);
        btnOcultar.setVisible(false);
        txtContraseña.setEchoChar('●');
    }//GEN-LAST:event_btnOcultarMouseClicked

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        btnVer.setVisible(false);
        btnOcultar.setVisible(true);
        txtContraseña.setEchoChar((char)0);
    }//GEN-LAST:event_btnVerMouseClicked

    private void txtUsername1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsername1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1KeyReleased
    int x, y;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x=evt.getX();
      y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x,point.y-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btbEnviarCodigo;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnBuscarDni;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnOcultar;
    private javax.swing.JLabel btnVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblErrorCodigo;
    private javax.swing.JLabel lblErrorUser;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblcontraseña1;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblcrearCuenta;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblnombres;
    private necesario.LabelIcon lblverificarCodigo;
    private necesario.LabelIcon lblverificarUsername;
    private RSMaterialComponent.RSButtonShape rSButtonShape16;
    private RSMaterialComponent.RSButtonShape rSButtonShape17;
    private RSMaterialComponent.RSButtonShape rSButtonShape18;
    private RSMaterialComponent.RSButtonShape rSButtonShape19;
    private RSMaterialComponent.RSButtonShape rSButtonShape20;
    private RSMaterialComponent.RSButtonShape rSButtonShape21;
    private RSMaterialComponent.RSButtonShape rSButtonShape22;
    private RSMaterialComponent.RSButtonShape rSButtonShape7;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    private necesario.TextField txtTelefono;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
