/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Pantallas.Trabajador.PrincipalTrabajador;
import Utilidades.Servicios;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point; 
import rojeru_san.complementos.RSEffectFade;
import rsutilities.RSUtilities;

/**
 *
 * @author chave
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        
        //this.setExtendedState(IniciarSesion.MAXIMIZED_BOTH);
        initComponents();          
        this.setLocationRelativeTo(null);
        btnOcultar.setVisible(false);
        RSEffectFade.setFadeWindowIn(this, 30,0.15f);
        RSUtilities.setOpaqueVentana(this, false);    
        RSUtilities.setOpacityComponente(this.panel, 0);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        lblOlvidasteContra = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JLabel();
        labelIcon1 = new necesario.LabelIcon();
        jPanel1 = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JLabel();
        txtUsuario = new RSMaterialComponent.RSTextFieldMaterial();
        txtPassword = new RSMaterialComponent.RSPasswordMaterial();
        btnOcultar = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        lblfaltauser = new javax.swing.JLabel();
        lblfaltacontra = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        rSButtonShape1 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape2 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape4 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape3 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape5 = new RSMaterialComponent.RSButtonShape();
        rSSwitch1 = new RSMaterialComponent.RSSwitch();
        rSSwitch3 = new RSMaterialComponent.RSSwitch();
        rSSwitch2 = new RSMaterialComponent.RSSwitch();
        rSSwitch4 = new RSMaterialComponent.RSSwitch();
        rSSwitch5 = new RSMaterialComponent.RSSwitch();
        btnClose = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });

        rSPanelBorder1.setBackground(new java.awt.Color(41, 41, 51));
        rSPanelBorder1.setBgBorder(new java.awt.Color(41, 41, 51));
        rSPanelBorder1.setRound(50);
        rSPanelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOlvidasteContra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOlvidasteContra.setForeground(new java.awt.Color(255, 255, 255));
        lblOlvidasteContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOlvidasteContra.setText("Olvidaste tu contraseña?");
        lblOlvidasteContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvidasteContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvidasteContraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOlvidasteContraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOlvidasteContraMouseExited(evt);
            }
        });
        rSPanelBorder1.add(lblOlvidasteContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 180, -1));

        btnCrearCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseExited(evt);
            }
        });
        rSPanelBorder1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 100, -1));

        labelIcon1.setBackground(new java.awt.Color(214, 33, 124));
        labelIcon1.setForeground(new java.awt.Color(214, 33, 124));
        labelIcon1.setBgTransparent(true);
        labelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        labelIcon1.setOpaque(true);
        rSPanelBorder1.add(labelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 70, 90, 90));

        jPanel1.setBackground(new java.awt.Color(48, 48, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setBackground(new java.awt.Color(48, 48, 60));
        btnIniciarSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.setOpaque(true);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 40));

        txtUsuario.setBackground(new java.awt.Color(68, 68, 78));
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(68, 68, 78), 1, true));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setColorMaterial(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtUsuario.setPhColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setPlaceholder("           USUARIO");
        txtUsuario.setSelectionColor(new java.awt.Color(48, 48, 60));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, -1));

        txtPassword.setBackground(new java.awt.Color(68, 68, 78));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setColorMaterial(new java.awt.Color(68, 68, 78));
        txtPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPassword.setPhColor(new java.awt.Color(255, 255, 255));
        txtPassword.setPlaceholder("       CONTRASEÑA");
        txtPassword.setSelectionColor(new java.awt.Color(48, 48, 60));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, -1));

        btnOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24wthide.png"))); // NOI18N
        btnOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOcultarMouseClicked(evt);
            }
        });
        jPanel1.add(btnOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24wtshow.png"))); // NOI18N
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        jPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        lblfaltauser.setBackground(new java.awt.Color(255, 0, 0));
        lblfaltauser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblfaltauser.setForeground(new java.awt.Color(255, 0, 0));
        lblfaltauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblfaltauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 20));

        lblfaltacontra.setBackground(new java.awt.Color(255, 0, 0));
        lblfaltacontra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblfaltacontra.setForeground(new java.awt.Color(255, 0, 0));
        lblfaltacontra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblfaltacontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 20));

        lblestado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblestado.setForeground(new java.awt.Color(255, 0, 0));
        lblestado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 240, 260, 20));

        rSPanelBorder1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 280, 280));

        rSButtonShape1.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape1.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape1.setBorderPainted(false);
        rSButtonShape1.setDefaultCapable(false);
        rSButtonShape1.setFocusPainted(false);
        rSButtonShape1.setFocusable(false);
        rSPanelBorder1.add(rSButtonShape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 40, 20));

        rSButtonShape2.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape2.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape2.setBorderPainted(false);
        rSButtonShape2.setDefaultCapable(false);
        rSButtonShape2.setFocusPainted(false);
        rSButtonShape2.setFocusable(false);
        rSButtonShape2.setForegroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape2.setForegroundText(new java.awt.Color(214, 33, 124));
        rSPanelBorder1.add(rSButtonShape2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 40, 20));

        rSButtonShape4.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape4.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape4.setBorderPainted(false);
        rSButtonShape4.setDefaultCapable(false);
        rSButtonShape4.setFocusPainted(false);
        rSButtonShape4.setFocusable(false);
        rSPanelBorder1.add(rSButtonShape4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 50, 20));

        rSButtonShape3.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape3.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape3.setBorderPainted(false);
        rSButtonShape3.setDefaultCapable(false);
        rSButtonShape3.setFocusPainted(false);
        rSButtonShape3.setFocusable(false);
        rSPanelBorder1.add(rSButtonShape3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 60, 20));

        rSButtonShape5.setBackground(new java.awt.Color(214, 33, 124));
        rSButtonShape5.setBackgroundHover(new java.awt.Color(214, 33, 124));
        rSButtonShape5.setBorderPainted(false);
        rSButtonShape5.setDefaultCapable(false);
        rSButtonShape5.setFocusPainted(false);
        rSButtonShape5.setFocusable(false);
        rSPanelBorder1.add(rSButtonShape5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 20));

        rSSwitch1.setBackground(new java.awt.Color(214, 33, 124));
        rSSwitch1.setForeground(new java.awt.Color(214, 33, 124));
        rSSwitch1.setBgButton(new java.awt.Color(214, 33, 124));
        rSSwitch1.setBgOff(new java.awt.Color(214, 33, 124));
        rSSwitch1.setBgOn(new java.awt.Color(214, 33, 124));
        rSSwitch1.setFocusable(false);
        rSPanelBorder1.add(rSSwitch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, 30));

        rSSwitch3.setBackground(new java.awt.Color(214, 33, 124));
        rSSwitch3.setForeground(new java.awt.Color(214, 33, 124));
        rSSwitch3.setBgButton(new java.awt.Color(214, 33, 124));
        rSSwitch3.setBgOff(new java.awt.Color(214, 33, 124));
        rSSwitch3.setBgOn(new java.awt.Color(214, 33, 124));
        rSSwitch3.setFocusable(false);
        rSPanelBorder1.add(rSSwitch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 30));

        rSSwitch2.setBackground(new java.awt.Color(214, 33, 124));
        rSSwitch2.setForeground(new java.awt.Color(214, 33, 124));
        rSSwitch2.setBgButton(new java.awt.Color(214, 33, 124));
        rSSwitch2.setBgOff(new java.awt.Color(214, 33, 124));
        rSSwitch2.setBgOn(new java.awt.Color(214, 33, 124));
        rSSwitch2.setFocusable(false);
        rSPanelBorder1.add(rSSwitch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 30));

        rSSwitch4.setBackground(new java.awt.Color(214, 33, 124));
        rSSwitch4.setForeground(new java.awt.Color(214, 33, 124));
        rSSwitch4.setBgButton(new java.awt.Color(214, 33, 124));
        rSSwitch4.setBgOff(new java.awt.Color(214, 33, 124));
        rSSwitch4.setBgOn(new java.awt.Color(214, 33, 124));
        rSSwitch4.setFocusable(false);
        rSPanelBorder1.add(rSSwitch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 30));

        rSSwitch5.setBackground(new java.awt.Color(214, 33, 124));
        rSSwitch5.setForeground(new java.awt.Color(214, 33, 124));
        rSSwitch5.setBgButton(new java.awt.Color(214, 33, 124));
        rSSwitch5.setBgOff(new java.awt.Color(214, 33, 124));
        rSSwitch5.setBgOn(new java.awt.Color(214, 33, 124));
        rSSwitch5.setFocusable(false);
        rSPanelBorder1.add(rSSwitch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 30));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24wtclose.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        rSPanelBorder1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 30));

        jLabel6.setBackground(new java.awt.Color(41, 41, 51));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INICIAR SESION");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setOpaque(true);
        rSPanelBorder1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 440, 40));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked
    int x , y;
    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
      x=evt.getX();
      y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
      Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x,point.y-y);
    }//GEN-LAST:event_panelMouseDragged

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        btnVer.setVisible(false);
        btnOcultar.setVisible(true);
        txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnVerMouseClicked

    private void btnOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseClicked
        ocultarContra();
    }//GEN-LAST:event_btnOcultarMouseClicked

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        lblfaltauser.setText(null);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        lblfaltacontra.setText(null);
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
         //Usuario user ;
        String username = txtUsuario.getText();
        String password = new String(txtPassword.getPassword()).trim();
        if(username.equals(""))
        {
            this.lblfaltauser.setText("Este campo es requerido.");
        }
        if(password.equals("")){
            this.lblfaltacontra.setText("Este campo es requerido.");
        }
        if(!username.equals("")&&!password.equals(""))
        { 
                if(Servicios.validarUsuario(username,password)){     
                    lblestado.setForeground(Color.GREEN);                
                    lblestado.setText("Usuario autenticado"); 
                    ocultarForm();
                    abrirForm();
                }
                else{
                    lblestado.setForeground(Color.RED);
                    lblestado.setText("Las credenciales no son correctas.");
                } 
            
            
        }    
    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    private void btnCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaMouseClicked
        CrearCuenta crear = new CrearCuenta(this);
        crear.setVisible(true);
    }//GEN-LAST:event_btnCrearCuentaMouseClicked

    private void btnCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaMouseEntered
        btnCrearCuenta.setForeground(Color.green);
    }//GEN-LAST:event_btnCrearCuentaMouseEntered

    private void btnCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaMouseExited
       btnCrearCuenta.setForeground(Color.white);
    }//GEN-LAST:event_btnCrearCuentaMouseExited

    private void lblOlvidasteContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidasteContraMouseClicked
        
    }//GEN-LAST:event_lblOlvidasteContraMouseClicked

    private void lblOlvidasteContraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidasteContraMouseEntered
        lblOlvidasteContra.setForeground(Color.green);
    }//GEN-LAST:event_lblOlvidasteContraMouseEntered

    private void lblOlvidasteContraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidasteContraMouseExited
        lblOlvidasteContra.setForeground(Color.white);
    }//GEN-LAST:event_lblOlvidasteContraMouseExited

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
       btnIniciarSesion.setBackground(new Color( 48,48,60));
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
       btnIniciarSesion.setBackground(new Color(214,33,124));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnCrearCuenta;
    private javax.swing.JLabel btnIniciarSesion;
    private javax.swing.JLabel btnOcultar;
    private javax.swing.JLabel btnVer;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private necesario.LabelIcon labelIcon1;
    private javax.swing.JLabel lblOlvidasteContra;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblfaltacontra;
    private javax.swing.JLabel lblfaltauser;
    private javax.swing.JPanel panel;
    private RSMaterialComponent.RSButtonShape rSButtonShape1;
    private RSMaterialComponent.RSButtonShape rSButtonShape2;
    private RSMaterialComponent.RSButtonShape rSButtonShape3;
    private RSMaterialComponent.RSButtonShape rSButtonShape4;
    private RSMaterialComponent.RSButtonShape rSButtonShape5;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSSwitch rSSwitch1;
    private RSMaterialComponent.RSSwitch rSSwitch2;
    private RSMaterialComponent.RSSwitch rSSwitch3;
    private RSMaterialComponent.RSSwitch rSSwitch4;
    private RSMaterialComponent.RSSwitch rSSwitch5;
    private RSMaterialComponent.RSPasswordMaterial txtPassword;
    private RSMaterialComponent.RSTextFieldMaterial txtUsuario;
    // End of variables declaration//GEN-END:variables
    public void ocultarForm() {
        this.setVisible(false); 
        reiniciarControles();
    }
    private void ocultarContra() {
        btnVer.setVisible(true);
        btnOcultar.setVisible(false);
        txtPassword.setEchoChar('●');

    }
    private void reiniciarControles() {
        this.setLocationRelativeTo(null);
        ocultarContra();   
        lblfaltacontra.setText(null);
        lblfaltauser.setText(null);
        txtPassword.setText(null);
        txtUsuario.setText(null);
        lblestado.setText(null);
    } 

    private void abrirForm() {
        PrincipalTrabajador JFTrabajador = new PrincipalTrabajador();
        JFTrabajador.setVisible(true);
    }
   
}
