/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas.Trabajador;

import Utilidades.Servicios;
import Utilidades.Arrays;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chave
 */
public class pnlClientes extends javax.swing.JPanel {

    /**
     * Creates new form pnlClientes
     */
    String tipodoc = "RUC";

    public pnlClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new rojerusan.RSPanelEffect();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new RSMaterialComponent.RSTableMetroCustom();
        jLabel1 = new javax.swing.JLabel();
        btnDni = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnRuc = new RSMaterialComponent.RSButtonMaterialIconOne();
        txtBuscaCliente = new RSMaterialComponent.RSTextFieldMaterialIcon();
        pnlEditar = new javax.swing.JPanel();
        txtNombres = new necesario.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtDocumento = new necesario.TextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new necesario.TextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new necesario.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEditAddCliente = new javax.swing.JLabel();
        cbTipo = new RSMaterialComponent.RSComboBoxMaterial();
        cbContacto = new RSMaterialComponent.RSComboBoxMaterial();
        btnAceptarEdit = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnCancelarEdit = new RSMaterialComponent.RSButtonMaterialIconOne();
        pnlDir = new rojerusan.RSPanelEffect();
        pnlTablaDir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnEditDir = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAddDir = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnDeleteDir = new RSMaterialComponent.RSButtonMaterialIconOne();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDir = new RSMaterialComponent.RSTableMetroCustom();
        pnlAgregarEditarDir = new javax.swing.JPanel();
        lblestadoDir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDepartamento = new necesario.TextField();
        jLabel7 = new javax.swing.JLabel();
        txtdistrito = new necesario.TextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtProvincia = new necesario.TextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReferencia = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        btnCancelarEditDir = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAceptarEditDir = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnEditCliente = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAddCliente = new RSMaterialComponent.RSButtonMaterialIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla.setName("pnlTabla"); // NOI18N

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nro Doc", "Tipo Doc", "Nombres", "Apellidos", "Telefono", "Canal Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setBackgoundHead(new java.awt.Color(214, 33, 124));
        tablaClientes.setBackgoundHover(new java.awt.Color(207, 123, 165));
        tablaClientes.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaClientes.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaClientes.setSelectionBackground(new java.awt.Color(207, 123, 165));
        jScrollPane1.setViewportView(tablaClientes);
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setMinWidth(150);
            tablaClientes.getColumnModel().getColumn(0).setMaxWidth(150);
            tablaClientes.getColumnModel().getColumn(1).setMinWidth(120);
            tablaClientes.getColumnModel().getColumn(1).setMaxWidth(130);
            tablaClientes.getColumnModel().getColumn(2).setMinWidth(120);
            tablaClientes.getColumnModel().getColumn(2).setMaxWidth(300);
            tablaClientes.getColumnModel().getColumn(3).setMinWidth(120);
            tablaClientes.getColumnModel().getColumn(3).setMaxWidth(300);
            tablaClientes.getColumnModel().getColumn(4).setMaxWidth(180);
            tablaClientes.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Clientes");

        btnDni.setBackground(new java.awt.Color(204, 204, 204));
        btnDni.setText("DNI");
        btnDni.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnDni.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnDni.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnDni.setForegroundText(new java.awt.Color(0, 0, 0));
        btnDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDni.setIconTextGap(29);
        btnDni.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CONTACT_MAIL);
        btnDni.setPaddingLeft(15);
        btnDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDniActionPerformed(evt);
            }
        });

        btnRuc.setBackground(new java.awt.Color(204, 204, 204));
        btnRuc.setText("RUC");
        btnRuc.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnRuc.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnRuc.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnRuc.setForegroundText(new java.awt.Color(0, 0, 0));
        btnRuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRuc.setIconTextGap(29);
        btnRuc.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_BOOKS);
        btnRuc.setPaddingLeft(15);
        btnRuc.setSelected(true);
        btnRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRucActionPerformed(evt);
            }
        });

        txtBuscaCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscaCliente.setColorIcon(new java.awt.Color(214, 33, 124));
        txtBuscaCliente.setColorMaterial(new java.awt.Color(214, 33, 124));
        txtBuscaCliente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscaCliente.setPhColor(new java.awt.Color(214, 33, 124));
        txtBuscaCliente.setPlaceholder("Buscar");
        txtBuscaCliente.setSelectionColor(new java.awt.Color(214, 33, 124));
        txtBuscaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDni, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(txtBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlTabla, "card3");

        pnlEditar.setBackground(new java.awt.Color(255, 255, 255));
        pnlEditar.setName("pnlEditar"); // NOI18N

        txtNombres.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtNombres.setName("txtNombres"); // NOI18N
        txtNombres.setPlaceholder("Nombres");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Apellidos");

        txtDocumento.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtDocumento.setForeground(new java.awt.Color(0, 0, 0));
        txtDocumento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDocumento.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtDocumento.setName("txtDocumento"); // NOI18N
        txtDocumento.setPlaceholder("Documento");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Tipo Documento");

        txtTelefono.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefono.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.setPlaceholder("Telefono");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Nombres");

        txtApellidos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtApellidos.setName("txtApellidos"); // NOI18N
        txtApellidos.setPlaceholder("Apellidos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Documento");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Canal Contacto");

        lblEditAddCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblEditAddCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEditAddCliente.setForeground(new java.awt.Color(214, 33, 124));
        lblEditAddCliente.setText("Editar Cliente");

        cbTipo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RUC", "DNI" }));

        cbContacto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        cbContacto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INSTAGRAM", "FACEBOOK", "TIKTOK", "PAGINA WEB" }));

        btnAceptarEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptarEdit.setText("Aceptar");
        btnAceptarEdit.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAceptarEdit.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAceptarEdit.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAceptarEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptarEdit.setIconTextGap(1);
        btnAceptarEdit.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DONE);
        btnAceptarEdit.setPaddingLeft(16);
        btnAceptarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditActionPerformed(evt);
            }
        });

        btnCancelarEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarEdit.setText("Cancelar");
        btnCancelarEdit.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnCancelarEdit.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCancelarEdit.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCancelarEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarEdit.setIconTextGap(1);
        btnCancelarEdit.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarEdit.setPaddingLeft(16);
        btnCancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditActionPerformed(evt);
            }
        });

        pnlTablaDir.setBackground(new java.awt.Color(255, 255, 255));
        pnlTablaDir.setName("pnlTablaDir"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("Direcciones");

        btnEditDir.setBackground(new java.awt.Color(204, 204, 204));
        btnEditDir.setText("Editar");
        btnEditDir.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnEditDir.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnEditDir.setForegroundText(new java.awt.Color(0, 0, 0));
        btnEditDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditDir.setIconTextGap(1);
        btnEditDir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditDir.setPaddingLeft(16);
        btnEditDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDirActionPerformed(evt);
            }
        });

        btnAddDir.setBackground(new java.awt.Color(204, 204, 204));
        btnAddDir.setText("Agregar ");
        btnAddDir.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAddDir.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAddDir.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAddDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddDir.setIconTextGap(1);
        btnAddDir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnAddDir.setPaddingLeft(16);
        btnAddDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDirActionPerformed(evt);
            }
        });

        btnDeleteDir.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteDir.setText("Eliminar ");
        btnDeleteDir.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnDeleteDir.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnDeleteDir.setForegroundText(new java.awt.Color(0, 0, 0));
        btnDeleteDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteDir.setIconTextGap(2);
        btnDeleteDir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnDeleteDir.setPaddingLeft(16);
        btnDeleteDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDirActionPerformed(evt);
            }
        });

        tablaDir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Departamento", "Provincia", "Distrito", "Direccion", "Referencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDir.setBackgoundHead(new java.awt.Color(214, 33, 124));
        tablaDir.setBackgoundHover(new java.awt.Color(207, 123, 124));
        tablaDir.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaDir.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaDir.setSelectionBackground(new java.awt.Color(214, 33, 124));
        jScrollPane2.setViewportView(tablaDir);
        if (tablaDir.getColumnModel().getColumnCount() > 0) {
            tablaDir.getColumnModel().getColumn(0).setMaxWidth(110);
        }

        javax.swing.GroupLayout pnlTablaDirLayout = new javax.swing.GroupLayout(pnlTablaDir);
        pnlTablaDir.setLayout(pnlTablaDirLayout);
        pnlTablaDirLayout.setHorizontalGroup(
            pnlTablaDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaDirLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaDirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablaDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTablaDirLayout.createSequentialGroup()
                        .addComponent(btnAddDir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditDir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(btnDeleteDir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        pnlTablaDirLayout.setVerticalGroup(
            pnlTablaDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaDirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(pnlTablaDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pnlDir.add(pnlTablaDir, "card2");

        pnlAgregarEditarDir.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgregarEditarDir.setName("pnlAgregarEditarDir"); // NOI18N

        lblestadoDir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblestadoDir.setText("Agregar Direccion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Distrito");

        txtDepartamento.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        txtDepartamento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDepartamento.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtDepartamento.setName("txtDocumento"); // NOI18N
        txtDepartamento.setPlaceholder("Departamento");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Provincia");

        txtdistrito.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtdistrito.setForeground(new java.awt.Color(0, 0, 0));
        txtdistrito.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtdistrito.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtdistrito.setName("txtApellidos"); // NOI18N
        txtdistrito.setPlaceholder("Apellidos");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Departamento");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Direccion");

        txtProvincia.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtProvincia.setForeground(new java.awt.Color(0, 0, 0));
        txtProvincia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProvincia.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtProvincia.setName("txtNombres"); // NOI18N
        txtProvincia.setPlaceholder("Provincia");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("Referencia");

        txtReferencia.setColumns(20);
        txtReferencia.setRows(3);
        txtReferencia.setWrapStyleWord(true);
        txtReferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(txtReferencia);

        txtDireccion.setColumns(20);
        txtDireccion.setRows(3);
        txtDireccion.setWrapStyleWord(true);
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(txtDireccion);

        btnCancelarEditDir.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarEditDir.setText("Cancelar");
        btnCancelarEditDir.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnCancelarEditDir.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCancelarEditDir.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCancelarEditDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarEditDir.setIconTextGap(1);
        btnCancelarEditDir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarEditDir.setPaddingLeft(16);
        btnCancelarEditDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditDirActionPerformed(evt);
            }
        });

        btnAceptarEditDir.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptarEditDir.setText("Aceptar");
        btnAceptarEditDir.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAceptarEditDir.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAceptarEditDir.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAceptarEditDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptarEditDir.setIconTextGap(1);
        btnAceptarEditDir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DONE);
        btnAceptarEditDir.setPaddingLeft(16);
        btnAceptarEditDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarEditarDirLayout = new javax.swing.GroupLayout(pnlAgregarEditarDir);
        pnlAgregarEditarDir.setLayout(pnlAgregarEditarDirLayout);
        pnlAgregarEditarDirLayout.setHorizontalGroup(
            pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                        .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                                .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAgregarEditarDirLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAceptarEditDir, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))
                    .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                        .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblestadoDir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarEditDir, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAgregarEditarDirLayout.setVerticalGroup(
            pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblestadoDir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(11, 11, 11)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAgregarEditarDirLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)
                        .addComponent(txtdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAgregarEditarDirLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarEditarDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEditDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarEditDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pnlDir.add(pnlAgregarEditarDir, "card3");

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(cbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(cbContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblEditAddCliente))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)))
                .addGap(31, 31, 31)
                .addComponent(pnlDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblEditAddCliente)
                .addGap(11, 11, 11)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(cbContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addComponent(pnlDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)))
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlPrincipal.add(pnlEditar, "card3");

        btnEditCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnEditCliente.setText("Editar Registro");
        btnEditCliente.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnEditCliente.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnEditCliente.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnEditCliente.setForegroundText(new java.awt.Color(0, 0, 0));
        btnEditCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditCliente.setIconTextGap(2);
        btnEditCliente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditCliente.setPaddingLeft(14);
        btnEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClienteActionPerformed(evt);
            }
        });

        btnAddCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnAddCliente.setText("Agregar Registro");
        btnAddCliente.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAddCliente.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnAddCliente.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAddCliente.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAddCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddCliente.setIconTextGap(2);
        btnAddCliente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnAddCliente.setPaddingLeft(14);
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClienteActionPerformed
        //Obtener indice seleccionado
        int indice = tablaClientes.getSelectedRow();
        if(indice != -1)
        {
            Object objeto = tablaClientes.getValueAt(indice,0);
            modificarEditar();
            Servicios.llenarArrayCliente(objeto.toString());
            llenarPanelEditCliente(Arrays.arrCliente);
            listarDirQuery(objeto.toString());
            this.pnlPrincipal.setPanelNormal(pnlEditar);
            lblEditAddCliente.setText("Editar Registro");
            btnEditCliente.setVisible(false);
            btnAddCliente.setVisible(false);
        }
        else{
            System.out.println("Selecciona un registro");
        }
    }//GEN-LAST:event_btnEditClienteActionPerformed
    private void btnDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDniActionPerformed
        if(!btnDni.isSelected()){
            tipodoc = "DNI";
            listarClientes("");  
            btnRuc.setSelected(false);
            btnDni.setSelected(true);
            
        }
    }//GEN-LAST:event_btnDniActionPerformed

    private void btnRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRucActionPerformed
        if(!btnRuc.isSelected()){
            tipodoc = "RUC";
            listarClientes("");
            btnRuc.setSelected(true);
            btnDni.setSelected(false);
        }
    }//GEN-LAST:event_btnRucActionPerformed

    private void txtBuscaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaClienteKeyReleased
        String buscar = txtBuscaCliente.getText();
        listarClientes(buscar);
    }//GEN-LAST:event_txtBuscaClienteKeyReleased

    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        btnEditCliente.setVisible(false);
        btnAddCliente.setVisible(false);
        this.pnlPrincipal.setPanelNormal(pnlEditar);        
        listarDirArray();
        modificarAgregar();
    }//GEN-LAST:event_btnAddClienteActionPerformed

    private void btnDeleteDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDirActionPerformed
        int indice = tablaDir.getSelectedRow();
        if(indice!=-1){
            Object cod = tablaDir.getValueAt(indice,0);
            if(lblEditAddCliente.getText().equals("Editar Registro")){
                Servicios.eliminarDir(cod.toString());
                listarDirQuery(txtDocumento.getText().trim());
            }else{
                listaDirec.remove(indice);
                listarDirArray();                            
            }
        }
    }//GEN-LAST:event_btnDeleteDirActionPerformed

    private void btnAddDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDirActionPerformed
        pnlDir.setPanelNormal(pnlAgregarEditarDir);
        btnAceptarEditDir.setText("Agregar");
    }//GEN-LAST:event_btnAddDirActionPerformed

    private void btnAceptarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditActionPerformed
        pnlPrincipal.setPanelNormal(pnlTabla);
        
        if(validarCampos()){
            if("Editar Registro".equals(lblEditAddCliente.getText())){
                actualizarCliente();


            }else{
                insertarCliente();

            }
        }
        else{
            System.out.println("Completa todos los campos");
        }
        limpiarPanelEdiAddCliente();
        btnEditCliente.setVisible(true);
        btnAddCliente.setVisible(true);
    }//GEN-LAST:event_btnAceptarEditActionPerformed

    private void btnCancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditActionPerformed
        this.pnlPrincipal.setPanelNormal(pnlTabla);        
        limpiarPanelEdiAddCliente();
        btnEditCliente.setVisible(true);
        btnAddCliente.setVisible(true);
    }//GEN-LAST:event_btnCancelarEditActionPerformed
    String codDirAntiguo ;
    int indDirAntiguo;
    private void btnEditDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDirActionPerformed
        int indice  = tablaDir.getSelectedRow();
        String doc=txtDocumento.getText();
        if(indice != -1){            
            llenarPanelEditarDir(listaDirec.get(indice));
            indDirAntiguo = indice;
            codDirAntiguo = listaDirec.get(indice)[0];
            pnlDir.setPanelNormal(pnlAgregarEditarDir);
        }
        
        
    }//GEN-LAST:event_btnEditDirActionPerformed

    private void btnCancelarEditDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditDirActionPerformed
        pnlDir.setPanelNormal(pnlTablaDir);
    }//GEN-LAST:event_btnCancelarEditDirActionPerformed
    List<String[]> listaDirec = new ArrayList<>();
    private void btnAceptarEditDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditDirActionPerformed
        if(!txtProvincia.getText().isEmpty()&&!txtDepartamento.getText().isEmpty()
                && !txtdistrito.getText().isEmpty()&& !txtDireccion.getText().isEmpty()
                &&!txtReferencia.getText().isEmpty()){
            if(lblEditAddCliente.getText().equals("Agregar Registro")){
                if(btnAceptarEditDir.getText().equals("Agregar")){
                    agregarDirArray();
                    
                }else{
                    actualizarDirArray();
                    
                }
                listarDirArray();
                pnlDir.setPanelNormal(pnlTablaDir);
            }else{
                if(btnAceptarEditDir.getText().equals("Agregar")){                    
                    agregarDirQuery();
                                      
                }else{
                    actualizarDirQuery();

                }  
                listarDirQuery(txtDocumento.getText());
                pnlDir.setPanelNormal(pnlTablaDir);

            }
            limpiarPanelEditarDir();
        }else{
            JOptionPane.showMessageDialog(null,"Completa los campos animal ");
        }
    }//GEN-LAST:event_btnAceptarEditDirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnAceptarEdit;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAceptarEditDir;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAddCliente;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAddDir;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCancelarEdit;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCancelarEditDir;
    private RSMaterialComponent.RSButtonMaterialIconOne btnDeleteDir;
    private RSMaterialComponent.RSButtonMaterialIconOne btnDni;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEditCliente;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEditDir;
    private RSMaterialComponent.RSButtonMaterialIconOne btnRuc;
    private RSMaterialComponent.RSComboBoxMaterial cbContacto;
    private RSMaterialComponent.RSComboBoxMaterial cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEditAddCliente;
    private javax.swing.JLabel lblestadoDir;
    private javax.swing.JPanel pnlAgregarEditarDir;
    private rojerusan.RSPanelEffect pnlDir;
    private javax.swing.JPanel pnlEditar;
    private rojerusan.RSPanelEffect pnlPrincipal;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTablaDir;
    private RSMaterialComponent.RSTableMetroCustom tablaClientes;
    private RSMaterialComponent.RSTableMetroCustom tablaDir;
    private necesario.TextField txtApellidos;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscaCliente;
    private necesario.TextField txtDepartamento;
    private javax.swing.JTextArea txtDireccion;
    private necesario.TextField txtDocumento;
    private necesario.TextField txtNombres;
    private necesario.TextField txtProvincia;
    private javax.swing.JTextArea txtReferencia;
    private necesario.TextField txtTelefono;
    private necesario.TextField txtdistrito;
    // End of variables declaration//GEN-END:variables

    public void listarClientes(String buscar) { 
        Servicios.listarClientes(tablaClientes, tipodoc, buscar);
    }
    public void listarDirQuery(String cliente){    
        listaDirec = new ArrayList<>();
        Servicios.listarDireccionQuery(tablaDir,cliente,listaDirec);
    }
    private void listarDirArray() {        
              DefaultTableModel modeloTabla = (DefaultTableModel) tablaDir.getModel();
        while(modeloTabla.getRowCount()>0){
            modeloTabla.removeRow(0);
        }
        String[] fila= new String[6];
        for (String [] dir : listaDirec) {
            fila[0] =  dir[0];
            fila[1] = dir[1];
            fila[2] = dir[2];
            fila[3] = dir[3];
            fila[4] =  dir[4];
            fila[5] =   dir[5];
            modeloTabla.addRow(fila);
        }
    }
    private void agregarDirQuery() {
        String [] nuevaDir = new String[6];
        
        if(0==listaDirec.size())
            nuevaDir[0] ="DIR-001";
        else{
            int ultimo = listaDirec.size()-1;   
            nuevaDir[0]= generarCodigo(listaDirec.get(ultimo)[0]);
        }        
        nuevaDir[1]=txtDepartamento.getText();
        nuevaDir[2]=txtProvincia.getText();
        nuevaDir[3]=txtdistrito.getText();
        nuevaDir[4]=txtDireccion.getText();
        nuevaDir[5]=txtReferencia.getText();        
        Servicios.agregarDirQuery(nuevaDir,txtDocumento.getText());
        listarDirQuery(txtDocumento.getText().trim());
    }   
    public void agregarDirArray(){
        String [] nuevaDir = new String[6];
        if(0==listaDirec.size())
            nuevaDir[0] ="DIR-001";
        else{
            int ultimo = listaDirec.size()-1;   
            nuevaDir[0]= generarCodigo(listaDirec.get(ultimo)[0]);
        }
        nuevaDir[1]=txtDepartamento.getText();
        nuevaDir[2]=txtProvincia.getText();
        nuevaDir[3]=txtdistrito.getText();
        nuevaDir[4]=txtDireccion.getText();
        nuevaDir[5]= txtReferencia.getText();
        listaDirec.add(nuevaDir);
        listarDirArray();
    }
   
    private void llenarPanelEditCliente(String[] arrCliente) {
        
        txtDocumento.setText(arrCliente[0]);
        txtNombres.setText(arrCliente[2]);
        txtApellidos.setText(arrCliente[3]);
        txtTelefono.setText(arrCliente[4]);
        cbTipo.setSelectedItem(arrCliente[1]);
        cbContacto.setSelectedItem(arrCliente[5]);      
        
    }
    private void modificarEditar(){
        lblEditAddCliente.setText("Editar Registro");
        btnAceptarEdit.setText("Editar");
    }

    private void modificarAgregar() {
        lblEditAddCliente.setText("Agregar Registro");
        btnAceptarEdit.setText("Agregar");

    }
    private void limpiarPanelEdiAddCliente(){
        listaDirec = new ArrayList<>();
        txtApellidos.setText(null);
        txtNombres.setText(null);
        txtDireccion.setText(null);
        txtDocumento.setText(null);
        txtTelefono.setText(null);
    }
    private void limpiarPanelEditarDir(){
        lblestadoDir.setText("Agregar Dirección");    
        txtDepartamento.setText(null);
        txtProvincia.setText(null);
        txtdistrito.setText(null);
        txtDireccion.setText(null);
        txtReferencia.setText(null); 
        btnAceptarEditDir.setText("Agregar");
    }
    String [] dirEditar ;
    private void llenarPanelEditarDir(String [] arrDir) {
        dirEditar = arrDir;
        lblestadoDir.setText("Editar Dirección");    
        txtDepartamento.setText(arrDir[1]);
        txtProvincia.setText(arrDir[2]);
        txtdistrito.setText(arrDir[3]);
        txtDireccion.setText(arrDir[4]);
        txtReferencia.setText(arrDir[5]); 
        btnAceptarEditDir.setText("Editar");
    }

    private String generarCodigo(String dirActual) {
        
        int numeroActual = Integer.parseInt(dirActual.substring(4));  
        int siguienteNumero = numeroActual + 1; 
        String siguienteDireccion = "DIR-" + String.format("%03d", siguienteNumero);
    
        return siguienteDireccion;        
    }
    
    private void actualizarDirArray() {
        
        dirEditar[0] = codDirAntiguo;
        dirEditar[1]=txtDepartamento.getText();
        dirEditar[2]=txtProvincia.getText();
        dirEditar[3]=txtdistrito.getText();
        dirEditar[4]=txtDireccion.getText();
        dirEditar[5]=txtReferencia.getText();  
        listaDirec.remove(indDirAntiguo);
        listaDirec.add(indDirAntiguo, dirEditar);

    }
    private void actualizarDirQuery() {
        dirEditar[1]=txtDepartamento.getText();
        dirEditar[2]=txtProvincia.getText();
        dirEditar[3]=txtdistrito.getText();
        dirEditar[4]=txtDireccion.getText();
        dirEditar[5]=txtReferencia.getText();  
        Servicios.actualizarDir(txtDocumento.getText(),dirEditar);
    }

    private boolean validarCampos() {
        return !"".equals(txtApellidos.getText())&&!""
                .equals(txtNombres.getText())&&!"".equals(txtDocumento
                .getText())&&!"".equals(txtTelefono.getText());
    }

    private void actualizarCliente() {        
        String [] actualizar = crearArrayCliente();
        String docA = Arrays.arrCliente[0];
        Servicios.actualizarCliente(docA, actualizar);
    }
    private void insertarCliente() {
        String [] insertar = crearArrayCliente();
        Servicios.agregarCliente(insertar);          
        Servicios.agregarDireccion(insertar[0],listaDirec);
    }
    public String[] crearArrayCliente() {
        String [] array = new String [6];
        String codCanal = null ;
        switch(cbContacto.getSelectedItem().toString()){
            case "INSTAGRAM":
                codCanal="CAN1";
                break;
            case "FACEBOOK":
                codCanal="CAN2";
                break;
            case "TIKTOK":
                codCanal="CAN3";
                break;
            case "PAGINA WEB":
                codCanal="CAN4";                
                break;
        }
        array[0] = txtDocumento.getText();
        array[1] = cbTipo.getSelectedItem().toString();
        array[2] = txtNombres.getText();
        array[3] = txtApellidos.getText();
        array[4] = txtTelefono.getText();
        array[5] = codCanal;
        return array;
    }


   

    

   

 
}
