/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas.Trabajador;

import Utilidades.Arrays;
import Utilidades.Foto;
import Utilidades.Servicios;
import java.io.IOException;




/**
 *
 * @author chave
 */
public class pnlProductos extends javax.swing.JPanel {

    /**
     * Creates new form pnlProductos
     */
    public pnlProductos() {
        initComponents();
        this.pnlPrincipal.setPanelNormal(pnlTabla);
        cbSubCategoria.removeAllItems();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new rojerusan.RSPanelEffect();
        pnlEditar = new javax.swing.JPanel();
        txtNombre = new necesario.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new necesario.TextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new necesario.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEditAddCliente = new javax.swing.JLabel();
        cbCategoria = new RSMaterialComponent.RSComboBoxMaterial();
        cbSubCategoria = new RSMaterialComponent.RSComboBoxMaterial();
        btnEditAgregar = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnCancelarEdit = new RSMaterialComponent.RSButtonMaterialIconOne();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblFoto = new javax.swing.JLabel();
        btnaddFoto = new RSMaterialComponent.RSButtonMaterialIconOne();
        cbProveedor = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbmarca = new RSMaterialComponent.RSComboBoxMaterial();
        btndeletfoto = new RSMaterialComponent.RSButtonMaterialIconOne();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new necesario.TextField();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new RSMaterialComponent.RSTableMetroCustom();
        jLabel1 = new javax.swing.JLabel();
        btnInstMu = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnArma = new RSMaterialComponent.RSButtonMaterialIconOne();
        txtBuscaProducto = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnDeco = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnjuegos = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAlmacen1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAlmacen2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAlmacen3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAddProducto = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnEditProducto = new RSMaterialComponent.RSButtonMaterialIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlEditar.setBackground(new java.awt.Color(255, 255, 255));
        pnlEditar.setName("pnlEditar"); // NOI18N

        txtNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.setPlaceholder("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Descripcion");

        txtCodigo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);
        txtCodigo.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtCodigo.setName("txtCodigo"); // NOI18N
        txtCodigo.setPlaceholder("Codigo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Categoria");

        txtPrecio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecio.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtPrecio.setName("txtPrecio"); // NOI18N
        txtPrecio.setPlaceholder("Precio");
        txtPrecio.setSoloNumeros(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Codigo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Precio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("SubCategoria");

        lblEditAddCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblEditAddCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEditAddCliente.setForeground(new java.awt.Color(214, 33, 124));
        lblEditAddCliente.setText("Editar Producto");

        cbCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ARMABLES3D", "INSTRUMENTOS MUSICALES", "DECORACIÓN Y HOGAR", "JUEGOS DE MESA" }));
        cbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCategoriaItemStateChanged(evt);
            }
        });

        cbSubCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        btnEditAgregar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditAgregar.setText("Aceptar");
        btnEditAgregar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnEditAgregar.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnEditAgregar.setForegroundText(new java.awt.Color(0, 0, 0));
        btnEditAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditAgregar.setIconTextGap(1);
        btnEditAgregar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DONE);
        btnEditAgregar.setPaddingLeft(16);
        btnEditAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAgregarActionPerformed(evt);
            }
        });

        btnCancelarEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarEdit.setText("Cancelar");
        btnCancelarEdit.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnCancelarEdit.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCancelarEdit.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCancelarEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarEdit.setIconTextGap(1);
        btnCancelarEdit.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarEdit.setPaddingLeft(16);
        btnCancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(3);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(txtDescripcion);

        lblFoto.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setName("lblfoto"); // NOI18N
        lblFoto.setOpaque(true);
        lblFoto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblFotoPropertyChange(evt);
            }
        });

        btnaddFoto.setBackground(new java.awt.Color(0, 153, 255));
        btnaddFoto.setText("Subir Foto");
        btnaddFoto.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnaddFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddFoto.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnaddFoto.setForegroundText(new java.awt.Color(0, 0, 0));
        btnaddFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnaddFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaddFoto.setIconTextGap(29);
        btnaddFoto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.OPEN_IN_BROWSER);
        btnaddFoto.setName("btnaddFoto"); // NOI18N
        btnaddFoto.setPaddingLeft(15);
        btnaddFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddFotoActionPerformed(evt);
            }
        });

        cbProveedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        cbProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRUPO ARSODA SAC" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Proveedor");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("Marca");

        cbmarca.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        cbmarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MAVBOMODELS" }));

        btndeletfoto.setBackground(new java.awt.Color(255, 0, 0));
        btndeletfoto.setText("Eliminar Foto");
        btndeletfoto.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btndeletfoto.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btndeletfoto.setForegroundText(new java.awt.Color(0, 0, 0));
        btndeletfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndeletfoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndeletfoto.setIconTextGap(29);
        btndeletfoto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btndeletfoto.setName("btnFoto"); // NOI18N
        btndeletfoto.setPaddingLeft(15);
        btndeletfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletfotoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Cantidad");

        txtCantidad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCantidad.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtCantidad.setName("txtCantidad"); // NOI18N
        txtCantidad.setPlaceholder("Cantidad");
        txtCantidad.setSoloNumeros(true);

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlEditarLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblEditAddCliente))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4)))
                        .addGap(36, 36, 36)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btndeletfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(btnaddFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(cbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(cbmarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEditarLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE))
                                    .addGroup(pnlEditarLayout.createSequentialGroup()
                                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7)
                                            .addComponent(cbSubCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                            .addComponent(cbProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 65, Short.MAX_VALUE))))))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(lblEditAddCliente)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(cbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(46, 46, 46))
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlEditarLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(13, 13, 13)
                                        .addComponent(cbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlEditarLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndeletfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnaddFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlPrincipal.add(pnlEditar, "card3");

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla.setName("pnlTabla"); // NOI18N

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "SubCategoria", "Stock", "Precio Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setBackgoundHead(new java.awt.Color(214, 33, 124));
        tablaProductos.setBackgoundHover(new java.awt.Color(207, 123, 165));
        tablaProductos.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaProductos.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaProductos.setSelectionBackground(new java.awt.Color(207, 123, 165));
        jScrollPane1.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(2).setMinWidth(300);
        }

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Productos");

        btnInstMu.setBackground(new java.awt.Color(204, 204, 204));
        btnInstMu.setText("INSTRUMENTOS MUSICALES");
        btnInstMu.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnInstMu.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnInstMu.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnInstMu.setForegroundText(new java.awt.Color(0, 0, 0));
        btnInstMu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInstMu.setIconTextGap(29);
        btnInstMu.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CONTACT_MAIL);
        btnInstMu.setPaddingLeft(15);
        btnInstMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstMuActionPerformed(evt);
            }
        });

        btnArma.setBackground(new java.awt.Color(204, 204, 204));
        btnArma.setText("ARMABLES3D");
        btnArma.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnArma.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnArma.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnArma.setForegroundText(new java.awt.Color(0, 0, 0));
        btnArma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnArma.setIconTextGap(29);
        btnArma.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_BOOKS);
        btnArma.setPaddingLeft(15);
        btnArma.setSelected(true);
        btnArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArmaActionPerformed(evt);
            }
        });

        txtBuscaProducto.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscaProducto.setColorIcon(new java.awt.Color(214, 33, 124));
        txtBuscaProducto.setColorMaterial(new java.awt.Color(214, 33, 124));
        txtBuscaProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscaProducto.setPhColor(new java.awt.Color(214, 33, 124));
        txtBuscaProducto.setPlaceholder("Buscar");
        txtBuscaProducto.setSelectionColor(new java.awt.Color(214, 33, 124));
        txtBuscaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaProductoKeyReleased(evt);
            }
        });

        btnDeco.setBackground(new java.awt.Color(204, 204, 204));
        btnDeco.setText("DECORACIÓN Y HOGAR");
        btnDeco.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnDeco.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnDeco.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnDeco.setForegroundText(new java.awt.Color(0, 0, 0));
        btnDeco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeco.setIconTextGap(29);
        btnDeco.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CONTACT_MAIL);
        btnDeco.setPaddingLeft(15);
        btnDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecoActionPerformed(evt);
            }
        });

        btnjuegos.setBackground(new java.awt.Color(204, 204, 204));
        btnjuegos.setText("JUEGOS DE MESA");
        btnjuegos.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnjuegos.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnjuegos.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnjuegos.setForegroundText(new java.awt.Color(0, 0, 0));
        btnjuegos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjuegos.setIconTextGap(29);
        btnjuegos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_BOOKS);
        btnjuegos.setPaddingLeft(15);
        btnjuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjuegosActionPerformed(evt);
            }
        });

        btnAlmacen1.setBackground(new java.awt.Color(204, 204, 204));
        btnAlmacen1.setText("ALMACEN 1");
        btnAlmacen1.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnAlmacen1.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAlmacen1.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnAlmacen1.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAlmacen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAlmacen1.setIconTextGap(29);
        btnAlmacen1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORE);
        btnAlmacen1.setPaddingLeft(15);
        btnAlmacen1.setSelected(true);
        btnAlmacen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacen1ActionPerformed(evt);
            }
        });

        btnAlmacen2.setBackground(new java.awt.Color(204, 204, 204));
        btnAlmacen2.setText("ALMACEN 2");
        btnAlmacen2.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnAlmacen2.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAlmacen2.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnAlmacen2.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAlmacen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAlmacen2.setIconTextGap(29);
        btnAlmacen2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORE);
        btnAlmacen2.setPaddingLeft(15);
        btnAlmacen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacen2ActionPerformed(evt);
            }
        });

        btnAlmacen3.setBackground(new java.awt.Color(204, 204, 204));
        btnAlmacen3.setText("ALMACEN 3");
        btnAlmacen3.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnAlmacen3.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAlmacen3.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnAlmacen3.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAlmacen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAlmacen3.setIconTextGap(29);
        btnAlmacen3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORE);
        btnAlmacen3.setPaddingLeft(15);
        btnAlmacen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacen3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(2, 2, 2))
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addComponent(btnArma, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnInstMu, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnjuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlmacen1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlmacen2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlmacen3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlmacen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlmacen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlmacen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInstMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );

        pnlPrincipal.add(pnlTabla, "card3");

        btnAddProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnAddProducto.setText("Agregar Registro");
        btnAddProducto.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAddProducto.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnAddProducto.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAddProducto.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAddProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddProducto.setIconTextGap(2);
        btnAddProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnAddProducto.setPaddingLeft(14);
        btnAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductoActionPerformed(evt);
            }
        });

        btnEditProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnEditProducto.setText("Editar Registro");
        btnEditProducto.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnEditProducto.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnEditProducto.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnEditProducto.setForegroundText(new java.awt.Color(0, 0, 0));
        btnEditProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditProducto.setIconTextGap(2);
        btnEditProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditProducto.setPaddingLeft(14);
        btnEditProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnEditProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addComponent(btnAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(643, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(73, 73, 73)))
        );
    }// </editor-fold>//GEN-END:initComponents
    String Categoria="CAT1" ;
    String Almacen = "ALM1";
    private void btnInstMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstMuActionPerformed
        if(!btnInstMu.isSelected()){
            Categoria = "CAT2";
             setSelectedFalse();
            btnInstMu.setSelected(true);
            listarProductos("");
        }
    }//GEN-LAST:event_btnInstMuActionPerformed

    private void btnArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArmaActionPerformed
        if(!btnArma.isSelected()){
            Categoria = "CAT1";
            setSelectedFalse();
            btnArma.setSelected(true);
            listarProductos("");
        }
    }//GEN-LAST:event_btnArmaActionPerformed

    private void txtBuscaProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProductoKeyReleased
        String buscar = txtBuscaProducto.getText();
        listarProductos(buscar);
    }//GEN-LAST:event_txtBuscaProductoKeyReleased

    private void btnEditAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAgregarActionPerformed
        pnlPrincipal.setPanelNormal(pnlTabla);

        if(validarCampos()){
            if("Editar Registro".equals(lblEditAddCliente.getText())){
                actualizarProducto();
                System.out.println("Registro editado");
            }else{
                agregarProducto();
                System.out.println("Registro agregado");
            }
        }
        else{
            System.out.println("Completa todos los campos");
        }
        listarProductos("");
        limpiarInputs();
        btnAddProducto.setVisible(true);
        btnEditProducto.setVisible(true);
        
    }//GEN-LAST:event_btnEditAgregarActionPerformed

    private void btnCancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditActionPerformed
        this.pnlPrincipal.setPanelNormal(pnlTabla);
        limpiarInputs();
        btnAddProducto.setVisible(true);
        btnEditProducto.setVisible(true);
       
    }//GEN-LAST:event_btnCancelarEditActionPerformed

    private void btnDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecoActionPerformed
        if(!btnDeco.isSelected()){
            setSelectedFalse();
            Categoria = "CAT3";
            btnDeco.setSelected(true);
            listarProductos("");
        }
    }//GEN-LAST:event_btnDecoActionPerformed

    private void btnjuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjuegosActionPerformed
        if(!btnjuegos.isSelected()){
            setSelectedFalse();
            Categoria = "CAT4";
            btnjuegos.setSelected(true);
            listarProductos("");
        }
    }//GEN-LAST:event_btnjuegosActionPerformed

    private void btnaddFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddFotoActionPerformed
        try {
            lblFoto.setIcon(null);
            Foto.subirFotoArchivo(lblFoto,this);
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_btnaddFotoActionPerformed

    private void btnAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductoActionPerformed
        btnEditProducto.setVisible(false);
        btnAddProducto.setVisible(false);
        modificarAgregar();
        this.pnlPrincipal.setPanelNormal(pnlEditar);
     
    }//GEN-LAST:event_btnAddProductoActionPerformed

    private void btnEditProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductoActionPerformed
        //Obtener indice seleccionado
        int indice = tablaProductos.getSelectedRow();
        if(indice != -1)
        {
            Object objeto = tablaProductos.getValueAt(indice,0);
            modificarEditar();
            Servicios.llenarArrayProducto(objeto.toString());
            llenarPanelEditProducto(Arrays.arrProducto);            
            this.pnlPrincipal.setPanelNormal(pnlEditar);
            lblEditAddCliente.setText("Editar Registro");
            btnEditProducto.setVisible(false);
            btnAddProducto.setVisible(false);
            
        }
        else{
            System.out.println("Selecciona un registro");
        }
    }//GEN-LAST:event_btnEditProductoActionPerformed

    private void cbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCategoriaItemStateChanged
        switch(cbCategoria.getSelectedItem().toString()){
            case "ARMABLES3D":
                llenarCombobox("CAT1");
                break;
            case "INSTRUMENTOS MUSICALES":
                llenarCombobox("CAT2");
                break;
            case "DECORACIÓN Y HOGAR":
                llenarCombobox("CAT3");
                break;
            case "JUEGOS DE MESA":
                llenarCombobox("CAT4");
                break;
        }
    }//GEN-LAST:event_cbCategoriaItemStateChanged

    private void btndeletfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletfotoActionPerformed
        if(lblFoto.getIcon()!=null)
            lblFoto.setIcon(null);
    }//GEN-LAST:event_btndeletfotoActionPerformed

    private void lblFotoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblFotoPropertyChange
        if(lblFoto.getIcon()!=null){
            btndeletfoto.setVisible(true);
        }else
            btndeletfoto.setVisible(false);
    }//GEN-LAST:event_lblFotoPropertyChange

    private void btnAlmacen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacen1ActionPerformed
        if(!btnAlmacen1.isSelected()){
            btnAlmacen1.setSelected(true);
            btnAlmacen2.setSelected(false);
            btnAlmacen3.setSelected(false);
            Almacen = "ALM1";
            listarProductos("");
        }
    }//GEN-LAST:event_btnAlmacen1ActionPerformed

    private void btnAlmacen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacen2ActionPerformed
        if(!btnAlmacen2.isSelected()){
            btnAlmacen1.setSelected(false);
            btnAlmacen2.setSelected(true);
            btnAlmacen3.setSelected(false);
            Almacen = "ALM2";
            listarProductos("");
        }
    }//GEN-LAST:event_btnAlmacen2ActionPerformed

    private void btnAlmacen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacen3ActionPerformed
        if(!btnAlmacen3.isSelected()){
            btnAlmacen1.setSelected(false);
            btnAlmacen2.setSelected(false);
            btnAlmacen3.setSelected(true);
            Almacen = "ALM3";
            listarProductos("");
        }
    }//GEN-LAST:event_btnAlmacen3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnAddProducto;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAlmacen1;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAlmacen2;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAlmacen3;
    private RSMaterialComponent.RSButtonMaterialIconOne btnArma;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCancelarEdit;
    private RSMaterialComponent.RSButtonMaterialIconOne btnDeco;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEditAgregar;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEditProducto;
    private RSMaterialComponent.RSButtonMaterialIconOne btnInstMu;
    private RSMaterialComponent.RSButtonMaterialIconOne btnaddFoto;
    private RSMaterialComponent.RSButtonMaterialIconOne btndeletfoto;
    private RSMaterialComponent.RSButtonMaterialIconOne btnjuegos;
    private RSMaterialComponent.RSComboBoxMaterial cbCategoria;
    private RSMaterialComponent.RSComboBoxMaterial cbProveedor;
    private RSMaterialComponent.RSComboBoxMaterial cbSubCategoria;
    private RSMaterialComponent.RSComboBoxMaterial cbmarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEditAddCliente;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnlEditar;
    private rojerusan.RSPanelEffect pnlPrincipal;
    private javax.swing.JPanel pnlTabla;
    private RSMaterialComponent.RSTableMetroCustom tablaProductos;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscaProducto;
    private necesario.TextField txtCantidad;
    private necesario.TextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private necesario.TextField txtNombre;
    private necesario.TextField txtPrecio;
    // End of variables declaration//GEN-END:variables
    private void setSelectedFalse(){
        btnArma.setSelected(false);
        btnDeco.setSelected(false);
        btnInstMu.setSelected(false);
        btnjuegos.setSelected(false); 
    }
    private boolean validarCampos() {
        return !"".equals(txtCodigo.getText())&&!"".equals(txtNombre.getText())
            &&!"".equals(txtPrecio.getText())&&!""
            .equals(txtDescripcion.getText());

    }

     private void modificarEditar(){
        lblEditAddCliente.setText("Editar Registro");
        btnEditAgregar.setText("Editar");
    }

    private void modificarAgregar() {
        lblEditAddCliente.setText("Agregar Registro");
        btnEditAgregar.setText("Agregar");
        int nuevo = Servicios.generarCodigo();
        txtCodigo.setText(generarCodigo(nuevo));
    }
    public static String generarCodigo(int numero) {        
        String codigo = String.format("P-%06d",numero);   
        return codigo;
    }
    
    private void llenarPanelEditProducto(Object[] arrProducto) {
        try {
            txtCodigo.setText(arrProducto[0].toString());
            txtNombre.setText(arrProducto[1].toString());
            txtDescripcion.setText(arrProducto[2].toString());
            txtPrecio.setText( arrProducto[3].toString());          
            cbCategoria.setSelectedItem(arrProducto[7]);  
            llenarCombobox(arrProducto[6].toString());
            cbSubCategoria.setSelectedItem(arrProducto[5]);
            System.out.println("");
            cbmarca.setSelectedItem(arrProducto[9]);
            if(arrProducto[8]!=null){
                byte [] array = (byte[]) arrProducto[8];
                Foto.cargarFotoLabel(lblFoto,array);
            }
            else
                lblFoto.setIcon(null); 
        } catch (IOException ex) {
            System.out.println("No se pudo cargar la foto");
        }
    }

    private void llenarCombobox(String idCate) {
        cbSubCategoria.removeAllItems();
        Servicios.llenarCombobox(idCate,cbSubCategoria);
    }

    public void listarProductos(String buscar) {
          Servicios.listarProductos(tablaProductos, Categoria, Almacen ,buscar);

    }
    private void limpiarInputs() {
        txtCodigo.setText(null);
        txtNombre.setText(null);
        txtDescripcion.setText(null);
        txtPrecio.setText(null);   
        txtCantidad.setText(null);
    }

    private void actualizarProducto() {
        String [] actualizar = crearArrayProducto();   
        byte[] bytes = null;
        if(lblFoto.getIcon()!=null)
              try {
                  bytes = Foto.obtenerFotoLabel(lblFoto);
        } catch (IOException ex) {
                  System.out.println("no se pudo guardar la foto");
        }
        else
            bytes = null;       
         
        Servicios.actualizarProducto(actualizar,bytes);
    }    
    private void agregarProducto() {
        String [] nuevPro = crearArrayProducto();
         byte[] bytes = null;
        if(lblFoto.getIcon()!=null)
              try {
                  bytes = Foto.obtenerFotoLabel(lblFoto);
        } catch (IOException ex) {
                  System.out.println("no se pudo guardar la foto");
        }
        else
            bytes = null; 
        Servicios.agregarProducto(nuevPro,bytes);

    }
     public String[] crearArrayProducto() {
    
        String [] array = new String [8];
        array[0] = txtCodigo.getText();
        array[1] = txtNombre.getText();
        array[2] = txtDescripcion.getText();
        array[3] = txtPrecio.getText();
        array[5] = cbSubCategoria.getSelectedItem().toString();
        array[4] = Servicios.getIdSubCate(array[5]);
        array[6] = cbmarca.getSelectedItem().toString();
        array[7] = txtCantidad.getText();
        array[8] = Almacen;
        return array;
    }

}
