/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas.Trabajador;

import rojeru_san.complementos.RSEffectFade;

/**
 *
 * @author chave
 */
public class PrincipalTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalTrabajador
     */
    public PrincipalTrabajador() {
        this.setExtendedState(PrincipalTrabajador.MAXIMIZED_BOTH);
        initComponents();
        RSEffectFade.setFadeWindowIn(this, 30,0.1f);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        btnProductos = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnVender = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnClientes = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnInicio = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSPanelBorder2 = new RSMaterialComponent.RSPanelBorder();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        rSPanelBorder3 = new RSMaterialComponent.RSPanelBorder();
        pnlPrincipal = new rojerusan.RSPanelEffect();
        pnlClientes = new Pantallas.Trabajador.pnlClientes();
        pnlProductos = new Pantallas.Trabajador.pnlProductos();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rSPanelBorder1.setBackground(new java.awt.Color(48, 48, 60));
        rSPanelBorder1.setBgBorder(new java.awt.Color(214, 33, 124));
        rSPanelBorder1.setBorderBottom(false);
        rSPanelBorder1.setBorderLeft(false);
        rSPanelBorder1.setBorderRight(false);
        rSPanelBorder1.setBorderTop(false);

        btnProductos.setBackground(new java.awt.Color(48, 48, 60));
        btnProductos.setText("             Productos");
        btnProductos.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnProductos.setHideActionText(true);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORE);
        btnProductos.setPaddingLeft(25);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnVender.setBackground(new java.awt.Color(48, 48, 60));
        btnVender.setText("             Vender");
        btnVender.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnVender.setHideActionText(true);
        btnVender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVender.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_CART);
        btnVender.setPaddingLeft(25);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(48, 48, 60));
        btnClientes.setText("             Clientes");
        btnClientes.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnClientes.setHideActionText(true);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SUPERVISOR_ACCOUNT);
        btnClientes.setPaddingLeft(25);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(48, 48, 60));
        btnSalir.setText("             Salir");
        btnSalir.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnSalir.setHideActionText(true);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS_POWER);
        btnSalir.setPaddingLeft(25);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(48, 48, 60));
        btnInicio.setText("             Inicio");
        btnInicio.setBackgroundHover(new java.awt.Color(214, 33, 124));
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.setHideActionText(true);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setIconTextGap(20);
        btnInicio.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnInicio.setMargin(new java.awt.Insets(3, 20, 3, 6));
        btnInicio.setPaddingLeft(25);

        javax.swing.GroupLayout rSPanelBorder1Layout = new javax.swing.GroupLayout(rSPanelBorder1);
        rSPanelBorder1.setLayout(rSPanelBorder1Layout);
        rSPanelBorder1Layout.setHorizontalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        rSPanelBorder1Layout.setVerticalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelBorder1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        rSPanelBorder2.setBackground(new java.awt.Color(48, 48, 60));
        rSPanelBorder2.setBgBorder(new java.awt.Color(214, 33, 124));
        rSPanelBorder2.setBorderBottom(false);
        rSPanelBorder2.setBorderLeft(false);
        rSPanelBorder2.setBorderRight(false);
        rSPanelBorder2.setBorderTop(false);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24wtclose.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24wtminimize-sign.png"))); // NOI18N
        btnMinimize.setText("minimize");
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorder2Layout = new javax.swing.GroupLayout(rSPanelBorder2);
        rSPanelBorder2.setLayout(rSPanelBorder2Layout);
        rSPanelBorder2Layout.setHorizontalGroup(
            rSPanelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelBorder2Layout.createSequentialGroup()
                .addContainerGap(784, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        rSPanelBorder2Layout.setVerticalGroup(
            rSPanelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelBorder3.setBackground(new java.awt.Color(68, 68, 78));
        rSPanelBorder3.setBgBorder(new java.awt.Color(214, 33, 124));
        rSPanelBorder3.setBorderBottom(false);
        rSPanelBorder3.setBorderLeft(false);
        rSPanelBorder3.setBorderRight(false);
        rSPanelBorder3.setBorderTop(false);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnlClientes.setName("pnlClientes"); // NOI18N
        pnlPrincipal.add(pnlClientes, "card2");

        pnlProductos.setName("pnlProductos"); // NOI18N
        pnlPrincipal.add(pnlProductos, "card3");

        javax.swing.GroupLayout rSPanelBorder3Layout = new javax.swing.GroupLayout(rSPanelBorder3);
        rSPanelBorder3.setLayout(rSPanelBorder3Layout);
        rSPanelBorder3Layout.setHorizontalGroup(
            rSPanelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelBorder3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorder3Layout.setVerticalGroup(
            rSPanelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSPanelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        if(!btnClientes.isSelected()){
            seleccionarFalse();
            btnClientes.setSelected(true);
            pnlClientes.listarClientes("");
            this.pnlPrincipal.setPanelNormal(pnlClientes);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        if(!btnProductos.isSelected()){
            seleccionarFalse();
            btnProductos.setSelected(true);
            pnlProductos.listarProductos("");
            pnlPrincipal.setPanelNormal(pnlProductos);
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if(!btnVender.isSelected()){
            seleccionarFalse();
            btnVender.setSelected(true);
            pnlProductos.listarProductos("");
            pnlPrincipal.setPanelNormal(pnlProductos);
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    public void seleccionarFalse() {
        btnInicio.setSelected(false);
        btnProductos.setSelected(false);
        btnVender.setSelected(false);
        btnClientes.setSelected(false);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnClientes;
    private javax.swing.JLabel btnClose;
    private RSMaterialComponent.RSButtonMaterialIconOne btnInicio;
    private javax.swing.JLabel btnMinimize;
    private RSMaterialComponent.RSButtonMaterialIconOne btnProductos;
    private RSMaterialComponent.RSButtonMaterialIconOne btnSalir;
    private RSMaterialComponent.RSButtonMaterialIconOne btnVender;
    private Pantallas.Trabajador.pnlClientes pnlClientes;
    private rojerusan.RSPanelEffect pnlPrincipal;
    private Pantallas.Trabajador.pnlProductos pnlProductos;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder2;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder3;
    // End of variables declaration//GEN-END:variables
}
